### PR TITLE
updates read_dicom for pydicom > 2.0.0

### LINKED ISSUE #160: pydicom >2.0.0 reads MRS with too many elements
Hiya, I've been having an issue with suspect since upgrading pydicom to 2.2.2.

To keep my application compatible with a 3rd party library I need to use pydicom>=2.1.2. Suspect was working perfectly with the old version of my application (using pydicom==1.2.0) but I'm now running into an error when trying to read dicom data. 

This issue comes up when reshaping the data_iter value in `io.dicom.load_dicom`

```
# turn the data into a numpy array
    data_iter = iter(dataset[0x5600, 0x0020])
    data = complex_array_from_iter(data_iter, shape=data_shape, chirality=-1)
```
The errors I get are always consistent with the test data I have available- there are always 4x too many data elements to reshape - tested with Philips and Siemens MRS dicom. 

E           ValueError: cannot reshape array of size 8192 into shape (2,1,1,1,1024)

E           ValueError: cannot reshape array of size 524288 into shape (32,1,1,1,4096)

E           ValueError: cannot reshape array of size 4096 into shape (1,1,1,1,1024)

Is this a known issue? I'm familiar with MRI but don't often work with raw MRS data, so I'm unsure how to address this. I'm happy to help with a fix if anyone is able to offer some insight as to where the missing factor of 4 is coming from!

### PR DESCRIPTION
**Pull request by laurencejackson**
Fixes issue when loading dicoms with pydicom versions >2.0.0

I've added a condition to explicitly state the conversion of the string stored in SpectroscopyData to a float32 array if the type of `type(SpectroscopyData)==bytes`. Previous versions of pydicom (tested with 1.2.0) load the SpectroscopyData field as `type(SpectroscopyData)====list`, so having this condition should not break compatibility with previous versions.

My test dicoms and all test data I was able to source does not contain a value in the conventional TR and TE fields. This resulted in a KeyError exception being raised when I attempted to read my test data. To resolve this I added a metadata dictionary that defines the parameters, dicom tags, and whether the value is required or not. The program will then loop over the keys in this dictionary and build a dictionary of values and raises an exception if a required tag is missing. Since the values for TR and TE in the returned MRSData object were kwargs with default values I have assumed that these are not always required to be set by the dicom.

I've also added a test function and test data for the load_dicom function.

I also had to add a few package to the requirements.txt to get the tests to run locally.

@bennyrowland, please let me know if you're happy with this solution and if you have any suggested changes.

resolves #160

### CODE REVIEW

**Comment by laurencejackson** [comment]
Just following up on this. @bennyrowland I spoke to you about the issue originally in #160, would you be happy to review the changes?

**Comment by darrencl** [comment]
Hey, thanks for the PR! I can confirm that this works for me. I got the issue as described in #160 and installing from this PR works.

Would be great if this can be merged/released.

**Comment by bennyrowland** [comment]
@laurencejackson - I can only apologise for dropping the ball on dealing with this PR, I am grateful for your effort in solving the problem and ignoring it for all this time was a poor repayment on your effort. @darrencl is stepping up to take on a maintainer role for Suspect which will hopefully breathe some fresh life into it.

@darrencl - I think it is past time that this fix got merged, unless you have addressed it in some other way? Once the gha pipeline is set up then we can hopefully rerun the checks and get it sorted. Perhaps you would like to have a look at the code and see what you think? It seems to me like the .nii file is not used anywhere and we should probably get rid of that before merging, but otherwise I think the changes look pretty sensible.

**Comment by darrencl** [comment]
@bennyrowland I did not address the issue in some other way, so I think it is a good idea to get this merged. As my comment above, I ran into this issue a couple of years ago and this PR helped.

I just had a look and I agree with you. It looks good to me, but the `.nii` file needs to be excluded. 

@laurencejackson Thanks for this! Could you rebase to the master branch to rerun checks on GHA and exclude the `.nii` file? I will merge once it passes the check.

**Comment by laurencejackson** [comment]
Thanks @bennyrowland and @darrencl, I'd completely forgotten about this! Glad the fix is still useful, I've updated from the main repo and removed the test file. But it doesn't look like I have permission to run the workflow, you'll need to approve that manually.

**Comment by darrencl** [comment]
Looks like it passed the checks! I will merge this.

**Pull request merged**
